complete --command spin --exclusive --no-files --description "Background job spinner"
complete --command spin --no-files --long-option style --short-option s --description "String of characters that make up the spinner"
complete --command spin --no-files --long-option format --short-option f --description "Customize the spinner display"
complete --command spin --no-files --long-option framesize --short-option n --description "Number of characters per frame"
complete --command spin --no-files --long-option interval --short-option i --description "Number of seconds between frames"
complete --command spin --no-files --long-option help --short-option h --description "Show usage help"
complete --command spin --short-option error --description "File to write errors to"
